// Generated by scripts/generate-curriculum-registry.mjs. Do not edit by hand.
import type { ExamSyllabus } from './types';

import e_jee_advanced from './jee-advanced.json';
import e_jee_main from './jee-main.json';
import e_math_olympiad from './math-olympiad.json';
import e_neet_ug from './neet-ug.json';
import e_nsejs from './nsejs.json';

export const EXAM_FILES = [
  e_jee_advanced,
  e_jee_main,
  e_math_olympiad,
  e_neet_ug,
  e_nsejs,
] as unknown as ExamSyllabus[];
