// Generated by scripts/generate-curriculum-registry.mjs. Do not edit by hand.
import type { CurriculumSubject } from './types';

import s_08_arts from './cbse-2026-27/08-arts.json';
import s_08_english from './cbse-2026-27/08-english.json';
import s_08_hindi from './cbse-2026-27/08-hindi.json';
import s_08_mathematics from './cbse-2026-27/08-mathematics.json';
import s_08_physical_education_and_well_being from './cbse-2026-27/08-physical-education-and-well-being.json';
import s_08_sanskrit from './cbse-2026-27/08-sanskrit.json';
import s_08_science from './cbse-2026-27/08-science.json';
import s_08_social_science from './cbse-2026-27/08-social-science.json';
import s_08_vocational_education from './cbse-2026-27/08-vocational-education.json';
import s_09_artificial_intelligence from './cbse-2026-27/09-artificial-intelligence.json';
import s_09_assamese from './cbse-2026-27/09-assamese.json';
import s_09_beauty_and_wellness from './cbse-2026-27/09-beauty-and-wellness.json';
import s_09_bengali from './cbse-2026-27/09-bengali.json';
import s_09_computer_applications from './cbse-2026-27/09-computer-applications.json';
import s_09_elements_of_book_keeping_and_accountancy from './cbse-2026-27/09-elements-of-book-keeping-and-accountancy.json';
import s_09_elements_of_business from './cbse-2026-27/09-elements-of-business.json';
import s_09_english from './cbse-2026-27/09-english.json';
import s_09_front_office_operations from './cbse-2026-27/09-front-office-operations.json';
import s_09_gujarati from './cbse-2026-27/09-gujarati.json';
import s_09_hindi from './cbse-2026-27/09-hindi.json';
import s_09_home_science from './cbse-2026-27/09-home-science.json';
import s_09_information_technology from './cbse-2026-27/09-information-technology.json';
import s_09_introduction_to_financial_markets from './cbse-2026-27/09-introduction-to-financial-markets.json';
import s_09_introduction_to_tourism from './cbse-2026-27/09-introduction-to-tourism.json';
import s_09_kannada from './cbse-2026-27/09-kannada.json';
import s_09_malayalam from './cbse-2026-27/09-malayalam.json';
import s_09_marathi from './cbse-2026-27/09-marathi.json';
import s_09_marketing_and_sales from './cbse-2026-27/09-marketing-and-sales.json';
import s_09_mathematics_at_advanced_level from './cbse-2026-27/09-mathematics-at-advanced-level.json';
import s_09_mathematics from './cbse-2026-27/09-mathematics.json';
import s_09_odia from './cbse-2026-27/09-odia.json';
import s_09_painting from './cbse-2026-27/09-painting.json';
import s_09_punjabi from './cbse-2026-27/09-punjabi.json';
import s_09_retail from './cbse-2026-27/09-retail.json';
import s_09_sanskrit from './cbse-2026-27/09-sanskrit.json';
import s_09_science_at_advanced_level from './cbse-2026-27/09-science-at-advanced-level.json';
import s_09_science from './cbse-2026-27/09-science.json';
import s_09_social_science from './cbse-2026-27/09-social-science.json';
import s_09_tamil from './cbse-2026-27/09-tamil.json';
import s_09_telugu_ap from './cbse-2026-27/09-telugu-ap.json';
import s_09_telugu_telangana from './cbse-2026-27/09-telugu-telangana.json';
import s_09_tili_kannada from './cbse-2026-27/09-tili-kannada.json';
import s_09_urdu_r1 from './cbse-2026-27/09-urdu-r1.json';
import s_09_urdu_r2 from './cbse-2026-27/09-urdu-r2.json';
import s_10_assamese from './cbse-2026-27/10-assamese.json';
import s_10_bengali from './cbse-2026-27/10-bengali.json';
import s_10_carnatic_music_melodic_instruments from './cbse-2026-27/10-carnatic-music-melodic-instruments.json';
import s_10_carnatic_music_percussion_instruments from './cbse-2026-27/10-carnatic-music-percussion-instruments.json';
import s_10_carnatic_music_vocal from './cbse-2026-27/10-carnatic-music-vocal.json';
import s_10_computer_applications from './cbse-2026-27/10-computer-applications.json';
import s_10_elements_of_book_keeping_and_accountancy from './cbse-2026-27/10-elements-of-book-keeping-and-accountancy.json';
import s_10_elements_of_business from './cbse-2026-27/10-elements-of-business.json';
import s_10_english_communicative from './cbse-2026-27/10-english-communicative.json';
import s_10_english_language_and_literature from './cbse-2026-27/10-english-language-and-literature.json';
import s_10_gujarati from './cbse-2026-27/10-gujarati.json';
import s_10_hindi_course_a from './cbse-2026-27/10-hindi-course-a.json';
import s_10_hindi_course_b from './cbse-2026-27/10-hindi-course-b.json';
import s_10_hindustani_music_melodic_instruments from './cbse-2026-27/10-hindustani-music-melodic-instruments.json';
import s_10_hindustani_music_percussion_instruments from './cbse-2026-27/10-hindustani-music-percussion-instruments.json';
import s_10_hindustani_music_vocal from './cbse-2026-27/10-hindustani-music-vocal.json';
import s_10_home_science from './cbse-2026-27/10-home-science.json';
import s_10_kannada from './cbse-2026-27/10-kannada.json';
import s_10_malayalam from './cbse-2026-27/10-malayalam.json';
import s_10_marathi from './cbse-2026-27/10-marathi.json';
import s_10_mathematics from './cbse-2026-27/10-mathematics.json';
import s_10_odia from './cbse-2026-27/10-odia.json';
import s_10_painting from './cbse-2026-27/10-painting.json';
import s_10_punjabi from './cbse-2026-27/10-punjabi.json';
import s_10_sanskrit_communicative from './cbse-2026-27/10-sanskrit-communicative.json';
import s_10_sanskrit from './cbse-2026-27/10-sanskrit.json';
import s_10_science from './cbse-2026-27/10-science.json';
import s_10_social_science from './cbse-2026-27/10-social-science.json';
import s_10_tamil from './cbse-2026-27/10-tamil.json';
import s_10_telugu_ap from './cbse-2026-27/10-telugu-ap.json';
import s_10_telugu_telangana from './cbse-2026-27/10-telugu-telangana.json';
import s_10_urdu_course_a from './cbse-2026-27/10-urdu-course-a.json';
import s_10_urdu_course_b from './cbse-2026-27/10-urdu-course-b.json';
import s_11_accountancy from './cbse-2026-27/11-accountancy.json';
import s_11_applied_art_commercial_art from './cbse-2026-27/11-applied-art-commercial-art.json';
import s_11_applied_mathematics from './cbse-2026-27/11-applied-mathematics.json';
import s_11_assamese from './cbse-2026-27/11-assamese.json';
import s_11_bengali from './cbse-2026-27/11-bengali.json';
import s_11_bharatanatyam_dance from './cbse-2026-27/11-bharatanatyam-dance.json';
import s_11_biology from './cbse-2026-27/11-biology.json';
import s_11_biotechnology from './cbse-2026-27/11-biotechnology.json';
import s_11_business_studies from './cbse-2026-27/11-business-studies.json';
import s_11_carnatic_music_melodic_instruments from './cbse-2026-27/11-carnatic-music-melodic-instruments.json';
import s_11_carnatic_music_percussion_instruments from './cbse-2026-27/11-carnatic-music-percussion-instruments.json';
import s_11_carnatic_music_vocal from './cbse-2026-27/11-carnatic-music-vocal.json';
import s_11_chemistry from './cbse-2026-27/11-chemistry.json';
import s_11_computer_science from './cbse-2026-27/11-computer-science.json';
import s_11_economics from './cbse-2026-27/11-economics.json';
import s_11_engineering_graphics from './cbse-2026-27/11-engineering-graphics.json';
import s_11_english_core from './cbse-2026-27/11-english-core.json';
import s_11_english_elective from './cbse-2026-27/11-english-elective.json';
import s_11_entrepreneurship from './cbse-2026-27/11-entrepreneurship.json';
import s_11_geography from './cbse-2026-27/11-geography.json';
import s_11_graphics_fine_arts from './cbse-2026-27/11-graphics-fine-arts.json';
import s_11_gujarati from './cbse-2026-27/11-gujarati.json';
import s_11_hindi_core from './cbse-2026-27/11-hindi-core.json';
import s_11_hindi_elective from './cbse-2026-27/11-hindi-elective.json';
import s_11_hindustani_music_melodic_instruments from './cbse-2026-27/11-hindustani-music-melodic-instruments.json';
import s_11_hindustani_music_percussion_instruments from './cbse-2026-27/11-hindustani-music-percussion-instruments.json';
import s_11_hindustani_music_vocal from './cbse-2026-27/11-hindustani-music-vocal.json';
import s_11_history from './cbse-2026-27/11-history.json';
import s_11_home_science from './cbse-2026-27/11-home-science.json';
import s_11_informatics_practices from './cbse-2026-27/11-informatics-practices.json';
import s_11_kannada from './cbse-2026-27/11-kannada.json';
import s_11_kathak_dance from './cbse-2026-27/11-kathak-dance.json';
import s_11_kathakali_dance from './cbse-2026-27/11-kathakali-dance.json';
import s_11_knowledge_traditions_and_practices_of_india from './cbse-2026-27/11-knowledge-traditions-and-practices-of-india.json';
import s_11_kuchipudi_dance from './cbse-2026-27/11-kuchipudi-dance.json';
import s_11_legal_studies from './cbse-2026-27/11-legal-studies.json';
import s_11_malayalam from './cbse-2026-27/11-malayalam.json';
import s_11_manipuri_dance from './cbse-2026-27/11-manipuri-dance.json';
import s_11_marathi from './cbse-2026-27/11-marathi.json';
import s_11_mathematics from './cbse-2026-27/11-mathematics.json';
import s_11_national_cadet_corps from './cbse-2026-27/11-national-cadet-corps.json';
import s_11_odia from './cbse-2026-27/11-odia.json';
import s_11_odissi_dance from './cbse-2026-27/11-odissi-dance.json';
import s_11_painting_fine_arts from './cbse-2026-27/11-painting-fine-arts.json';
import s_11_physical_education from './cbse-2026-27/11-physical-education.json';
import s_11_physics from './cbse-2026-27/11-physics.json';
import s_11_political_science from './cbse-2026-27/11-political-science.json';
import s_11_psychology from './cbse-2026-27/11-psychology.json';
import s_11_punjabi from './cbse-2026-27/11-punjabi.json';
import s_11_sanskrit_core from './cbse-2026-27/11-sanskrit-core.json';
import s_11_sanskrit_elective from './cbse-2026-27/11-sanskrit-elective.json';
import s_11_sculpture_fine_arts from './cbse-2026-27/11-sculpture-fine-arts.json';
import s_11_sociology from './cbse-2026-27/11-sociology.json';
import s_11_tamil from './cbse-2026-27/11-tamil.json';
import s_11_telugu_ap from './cbse-2026-27/11-telugu-ap.json';
import s_11_telugu_telangana from './cbse-2026-27/11-telugu-telangana.json';
import s_11_urdu_core from './cbse-2026-27/11-urdu-core.json';
import s_11_urdu_elective from './cbse-2026-27/11-urdu-elective.json';
import s_12_accountancy from './cbse-2026-27/12-accountancy.json';
import s_12_applied_art_commercial_art from './cbse-2026-27/12-applied-art-commercial-art.json';
import s_12_applied_mathematics from './cbse-2026-27/12-applied-mathematics.json';
import s_12_assamese from './cbse-2026-27/12-assamese.json';
import s_12_bengali from './cbse-2026-27/12-bengali.json';
import s_12_bharatanatyam_dance from './cbse-2026-27/12-bharatanatyam-dance.json';
import s_12_biology from './cbse-2026-27/12-biology.json';
import s_12_biotechnology from './cbse-2026-27/12-biotechnology.json';
import s_12_business_studies from './cbse-2026-27/12-business-studies.json';
import s_12_carnatic_music_melodic_instruments from './cbse-2026-27/12-carnatic-music-melodic-instruments.json';
import s_12_carnatic_music_percussion_instruments from './cbse-2026-27/12-carnatic-music-percussion-instruments.json';
import s_12_carnatic_music_vocal from './cbse-2026-27/12-carnatic-music-vocal.json';
import s_12_chemistry from './cbse-2026-27/12-chemistry.json';
import s_12_computer_science from './cbse-2026-27/12-computer-science.json';
import s_12_economics from './cbse-2026-27/12-economics.json';
import s_12_engineering_graphics from './cbse-2026-27/12-engineering-graphics.json';
import s_12_english_core from './cbse-2026-27/12-english-core.json';
import s_12_english_elective from './cbse-2026-27/12-english-elective.json';
import s_12_entrepreneurship from './cbse-2026-27/12-entrepreneurship.json';
import s_12_geography from './cbse-2026-27/12-geography.json';
import s_12_graphics_fine_arts from './cbse-2026-27/12-graphics-fine-arts.json';
import s_12_gujarati from './cbse-2026-27/12-gujarati.json';
import s_12_hindi_core from './cbse-2026-27/12-hindi-core.json';
import s_12_hindi_elective from './cbse-2026-27/12-hindi-elective.json';
import s_12_hindustani_music_melodic_instruments from './cbse-2026-27/12-hindustani-music-melodic-instruments.json';
import s_12_hindustani_music_percussion_instruments from './cbse-2026-27/12-hindustani-music-percussion-instruments.json';
import s_12_hindustani_music_vocal from './cbse-2026-27/12-hindustani-music-vocal.json';
import s_12_history from './cbse-2026-27/12-history.json';
import s_12_home_science from './cbse-2026-27/12-home-science.json';
import s_12_informatics_practices from './cbse-2026-27/12-informatics-practices.json';
import s_12_kannada from './cbse-2026-27/12-kannada.json';
import s_12_kathak_dance from './cbse-2026-27/12-kathak-dance.json';
import s_12_kathakali_dance from './cbse-2026-27/12-kathakali-dance.json';
import s_12_knowledge_traditions_and_practices_of_india from './cbse-2026-27/12-knowledge-traditions-and-practices-of-india.json';
import s_12_kuchipudi_dance from './cbse-2026-27/12-kuchipudi-dance.json';
import s_12_legal_studies from './cbse-2026-27/12-legal-studies.json';
import s_12_malayalam from './cbse-2026-27/12-malayalam.json';
import s_12_manipuri_dance from './cbse-2026-27/12-manipuri-dance.json';
import s_12_marathi from './cbse-2026-27/12-marathi.json';
import s_12_mathematics from './cbse-2026-27/12-mathematics.json';
import s_12_national_cadet_corps from './cbse-2026-27/12-national-cadet-corps.json';
import s_12_odia from './cbse-2026-27/12-odia.json';
import s_12_odissi_dance from './cbse-2026-27/12-odissi-dance.json';
import s_12_painting_fine_arts from './cbse-2026-27/12-painting-fine-arts.json';
import s_12_physical_education from './cbse-2026-27/12-physical-education.json';
import s_12_physics from './cbse-2026-27/12-physics.json';
import s_12_political_science from './cbse-2026-27/12-political-science.json';
import s_12_psychology from './cbse-2026-27/12-psychology.json';
import s_12_punjabi from './cbse-2026-27/12-punjabi.json';
import s_12_sanskrit_core from './cbse-2026-27/12-sanskrit-core.json';
import s_12_sanskrit_elective from './cbse-2026-27/12-sanskrit-elective.json';
import s_12_sculpture_fine_arts from './cbse-2026-27/12-sculpture-fine-arts.json';
import s_12_sociology from './cbse-2026-27/12-sociology.json';
import s_12_tamil from './cbse-2026-27/12-tamil.json';
import s_12_telugu_ap from './cbse-2026-27/12-telugu-ap.json';
import s_12_telugu_telangana from './cbse-2026-27/12-telugu-telangana.json';
import s_12_urdu_core from './cbse-2026-27/12-urdu-core.json';
import s_12_urdu_elective from './cbse-2026-27/12-urdu-elective.json';

export const SUBJECT_FILES = [
  s_08_arts,
  s_08_english,
  s_08_hindi,
  s_08_mathematics,
  s_08_physical_education_and_well_being,
  s_08_sanskrit,
  s_08_science,
  s_08_social_science,
  s_08_vocational_education,
  s_09_artificial_intelligence,
  s_09_assamese,
  s_09_beauty_and_wellness,
  s_09_bengali,
  s_09_computer_applications,
  s_09_elements_of_book_keeping_and_accountancy,
  s_09_elements_of_business,
  s_09_english,
  s_09_front_office_operations,
  s_09_gujarati,
  s_09_hindi,
  s_09_home_science,
  s_09_information_technology,
  s_09_introduction_to_financial_markets,
  s_09_introduction_to_tourism,
  s_09_kannada,
  s_09_malayalam,
  s_09_marathi,
  s_09_marketing_and_sales,
  s_09_mathematics_at_advanced_level,
  s_09_mathematics,
  s_09_odia,
  s_09_painting,
  s_09_punjabi,
  s_09_retail,
  s_09_sanskrit,
  s_09_science_at_advanced_level,
  s_09_science,
  s_09_social_science,
  s_09_tamil,
  s_09_telugu_ap,
  s_09_telugu_telangana,
  s_09_tili_kannada,
  s_09_urdu_r1,
  s_09_urdu_r2,
  s_10_assamese,
  s_10_bengali,
  s_10_carnatic_music_melodic_instruments,
  s_10_carnatic_music_percussion_instruments,
  s_10_carnatic_music_vocal,
  s_10_computer_applications,
  s_10_elements_of_book_keeping_and_accountancy,
  s_10_elements_of_business,
  s_10_english_communicative,
  s_10_english_language_and_literature,
  s_10_gujarati,
  s_10_hindi_course_a,
  s_10_hindi_course_b,
  s_10_hindustani_music_melodic_instruments,
  s_10_hindustani_music_percussion_instruments,
  s_10_hindustani_music_vocal,
  s_10_home_science,
  s_10_kannada,
  s_10_malayalam,
  s_10_marathi,
  s_10_mathematics,
  s_10_odia,
  s_10_painting,
  s_10_punjabi,
  s_10_sanskrit_communicative,
  s_10_sanskrit,
  s_10_science,
  s_10_social_science,
  s_10_tamil,
  s_10_telugu_ap,
  s_10_telugu_telangana,
  s_10_urdu_course_a,
  s_10_urdu_course_b,
  s_11_accountancy,
  s_11_applied_art_commercial_art,
  s_11_applied_mathematics,
  s_11_assamese,
  s_11_bengali,
  s_11_bharatanatyam_dance,
  s_11_biology,
  s_11_biotechnology,
  s_11_business_studies,
  s_11_carnatic_music_melodic_instruments,
  s_11_carnatic_music_percussion_instruments,
  s_11_carnatic_music_vocal,
  s_11_chemistry,
  s_11_computer_science,
  s_11_economics,
  s_11_engineering_graphics,
  s_11_english_core,
  s_11_english_elective,
  s_11_entrepreneurship,
  s_11_geography,
  s_11_graphics_fine_arts,
  s_11_gujarati,
  s_11_hindi_core,
  s_11_hindi_elective,
  s_11_hindustani_music_melodic_instruments,
  s_11_hindustani_music_percussion_instruments,
  s_11_hindustani_music_vocal,
  s_11_history,
  s_11_home_science,
  s_11_informatics_practices,
  s_11_kannada,
  s_11_kathak_dance,
  s_11_kathakali_dance,
  s_11_knowledge_traditions_and_practices_of_india,
  s_11_kuchipudi_dance,
  s_11_legal_studies,
  s_11_malayalam,
  s_11_manipuri_dance,
  s_11_marathi,
  s_11_mathematics,
  s_11_national_cadet_corps,
  s_11_odia,
  s_11_odissi_dance,
  s_11_painting_fine_arts,
  s_11_physical_education,
  s_11_physics,
  s_11_political_science,
  s_11_psychology,
  s_11_punjabi,
  s_11_sanskrit_core,
  s_11_sanskrit_elective,
  s_11_sculpture_fine_arts,
  s_11_sociology,
  s_11_tamil,
  s_11_telugu_ap,
  s_11_telugu_telangana,
  s_11_urdu_core,
  s_11_urdu_elective,
  s_12_accountancy,
  s_12_applied_art_commercial_art,
  s_12_applied_mathematics,
  s_12_assamese,
  s_12_bengali,
  s_12_bharatanatyam_dance,
  s_12_biology,
  s_12_biotechnology,
  s_12_business_studies,
  s_12_carnatic_music_melodic_instruments,
  s_12_carnatic_music_percussion_instruments,
  s_12_carnatic_music_vocal,
  s_12_chemistry,
  s_12_computer_science,
  s_12_economics,
  s_12_engineering_graphics,
  s_12_english_core,
  s_12_english_elective,
  s_12_entrepreneurship,
  s_12_geography,
  s_12_graphics_fine_arts,
  s_12_gujarati,
  s_12_hindi_core,
  s_12_hindi_elective,
  s_12_hindustani_music_melodic_instruments,
  s_12_hindustani_music_percussion_instruments,
  s_12_hindustani_music_vocal,
  s_12_history,
  s_12_home_science,
  s_12_informatics_practices,
  s_12_kannada,
  s_12_kathak_dance,
  s_12_kathakali_dance,
  s_12_knowledge_traditions_and_practices_of_india,
  s_12_kuchipudi_dance,
  s_12_legal_studies,
  s_12_malayalam,
  s_12_manipuri_dance,
  s_12_marathi,
  s_12_mathematics,
  s_12_national_cadet_corps,
  s_12_odia,
  s_12_odissi_dance,
  s_12_painting_fine_arts,
  s_12_physical_education,
  s_12_physics,
  s_12_political_science,
  s_12_psychology,
  s_12_punjabi,
  s_12_sanskrit_core,
  s_12_sanskrit_elective,
  s_12_sculpture_fine_arts,
  s_12_sociology,
  s_12_tamil,
  s_12_telugu_ap,
  s_12_telugu_telangana,
  s_12_urdu_core,
  s_12_urdu_elective,
] as unknown as CurriculumSubject[];
