/**
 * Generates supabase/seed/cbse_2026_27_learning_outcomes.sql from the ingested
 * curriculum (src/lib/curriculum). One learning_outcomes row per chapter
 * outcome (or one per chapter when the document lists no outcomes), with a
 * stable code so submission_items.outcome_code can reference it.
 *
 *   npx tsx --tsconfig tsconfig.json scripts/generate-curriculum-seed.ts
 *
 * Idempotent SQL (ON CONFLICT DO UPDATE). Not applied automatically.
 */
import { writeFileSync } from 'node:fs';
import { CURRICULUM } from '../src/lib/curriculum';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const abbr = (subject: string) => subject.replace(/[^A-Za-z ]/g, '').split(' ').map(w => w.slice(0, 3)).join('').toUpperCase();

const rows: string[] = [];
for (const s of CURRICULUM) {
  const session = s.session.replace('-', '');
  s.units.forEach((u, ui) => {
    u.chapters.forEach((c, ci) => {
      const base = `CBSE${session}-${s.class}-${abbr(s.subject)}-U${ui + 1}-C${ci + 1}`;
      const outcomes = c.outcomes.length ? c.outcomes : [c.name];
      const desc = [`Chapter: ${c.name}`, c.formativeOnly ? 'Assessed formatively only' : null, `Source: ${s.source.url}`].filter(Boolean).join(' | ');
      outcomes.forEach((o, oi) => {
        rows.push(`  (${q(s.subject)}, ${q(s.class)}, ${q(u.name)}, ${q(`${base}-O${oi + 1}`)}, ${q(o)}, ${q(desc)})`);
      });
    });
  });
}

const sql = `-- Generated by scripts/generate-curriculum-seed.ts. Do not edit by hand.
-- CBSE ${CURRICULUM[0].session} learning outcomes for ${CURRICULUM.length} subjects (${rows.length} rows).
-- Idempotent: re-running updates names/descriptions in place. NOT YET APPLIED.
INSERT INTO public.learning_outcomes (subject, class, unit_name, outcome_code, outcome_name, description)
VALUES
${rows.join(',\n')}
ON CONFLICT (outcome_code) DO UPDATE
  SET subject = EXCLUDED.subject, class = EXCLUDED.class, unit_name = EXCLUDED.unit_name,
      outcome_name = EXCLUDED.outcome_name, description = EXCLUDED.description;
`;
writeFileSync('supabase/seed/cbse_2026_27_learning_outcomes.sql', sql);
console.log(`Wrote ${rows.length} learning outcomes.`);
